name = "GnssNavipedia"
uuid = "740e39a9-d825-4f41-ba2b-8ade44299295"
authors = ["Fernando Conde-Pumpido"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
